---
version: '3'
services:
  dvwa:
    image: wallarm/fast-example-dvwa-base
    networks:
      main:
        aliases:
          - dvwa

  fast:
    image: wallarm/fast
    restart: on-failure
    environment:
      WALLARM_API_TOKEN: BAMSCRT@0@0@BD+8NIfWD4AtzHDwm3A5TF9YQOacU1npnP/2sw7MdoR5JIuBtMbsvvrJS1fI8AIkBZ2tFRKfSYiQbN0hrf9APV8JUDDTKu5CwGlZxfseou0=
      TEST_RUN_POLICY_ID: 104
      CI_MODE: recording
      ALLOWED_HOSTS: dvwa
    networks:
      main:
        aliases:
          - fast

  selenium:
    image: selenium/standalone-firefox:latest
    logging:
      driver: none
    environment:
      http_proxy: http://fast:8080
    networks:
      main:
        aliases:
          - selenium

  test:
    image: wallarm/fast-example-dvwa-tests
    networks:
      main:

networks:
  main:
